### ISSUE TITLE
Fails with TypeError on todos.sort

### ISSUE THREAD

**Issue by elwayman02** [lint-todo/ember-template-lint-formatter-todo#4]
I tried installing this package in one of our projects today, but running with the formatter produced the following error:

```
% yarn ember-template-lint . --format @scalvert/ember-template-lint-formatter-todo
yarn run v1.22.4
$ /my-project/node_modules/.bin/ember-template-lint . --format @scalvert/ember-template-lint-formatter-todo
Calling the log method without passing the node is deprecated. Please ensure you pass node in the log method's result.
(node:77287) UnhandledPromiseRejectionWarning: TypeError: todos.sort is not a function
    at TodoSummaryFormatter.print (/my-project/node_modules/@scalvert/ember-template-lint-formatter-todo/index.js:18:8)
    at DefaultPrinter.print (/my-project/node_modules/ember-template-lint/lib/formatters/default.js:63:16)
    at run (/my-project/node_modules/ember-template-lint/bin/ember-template-lint.js:471:13)
```

**Comment by scalvert** [comment]
I believe this is resolved in the latest version of the formatter. Feel free to reopen if this is not the case.
